### ISSUE TITLE
Missing contact page

### ISSUE THREAD

**Issue by ThirtySomething** [Ay1tsMe/minimalWebsite#1]
Hi there,

thanks for your guide about ripping audio cds. I'm very interested in this guide and have some questions. Unfortunately your email contact page results in a 404-error. Maybe you want to fix that?

Rergards

Jochen aka
ThirtySomething

**Comment by Ay1tsMe** [comment]
I'm glad you enjoyed my blog. The main reason my I haven't set up the contact page yet is because I want to set up an email server specifically for this domain instead of using my personal email. 

I'll try get around to it this week and let you know when its fixed. If you still want to contact me, I have my discord information available that you can use.

**Comment by Ay1tsMe** [comment]
I added my email address so feel free to send me an email!
